// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/formatsv1/formats.proto

package formatsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FormatService_ListFormats_FullMethodName          = "/muxcore.formats.v1.FormatService/ListFormats"
	FormatService_CreateFormat_FullMethodName         = "/muxcore.formats.v1.FormatService/CreateFormat"
	FormatService_UpdateFormat_FullMethodName         = "/muxcore.formats.v1.FormatService/UpdateFormat"
	FormatService_DeleteFormat_FullMethodName         = "/muxcore.formats.v1.FormatService/DeleteFormat"
	FormatService_ListProfiles_FullMethodName         = "/muxcore.formats.v1.FormatService/ListProfiles"
	FormatService_CreateProfile_FullMethodName        = "/muxcore.formats.v1.FormatService/CreateProfile"
	FormatService_UpdateProfile_FullMethodName        = "/muxcore.formats.v1.FormatService/UpdateProfile"
	FormatService_DeleteProfile_FullMethodName        = "/muxcore.formats.v1.FormatService/DeleteProfile"
	FormatService_ScoreRelease_FullMethodName         = "/muxcore.formats.v1.FormatService/ScoreRelease"
	FormatService_ParseQuality_FullMethodName         = "/muxcore.formats.v1.FormatService/ParseQuality"
	FormatService_SyncTrashGuides_FullMethodName      = "/muxcore.formats.v1.FormatService/SyncTrashGuides"
	FormatService_ListReleaseProfiles_FullMethodName  = "/muxcore.formats.v1.FormatService/ListReleaseProfiles"
	FormatService_UpsertReleaseProfile_FullMethodName = "/muxcore.formats.v1.FormatService/UpsertReleaseProfile"
	FormatService_DeleteReleaseProfile_FullMethodName = "/muxcore.formats.v1.FormatService/DeleteReleaseProfile"
)

// FormatServiceClient is the client API for FormatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormatServiceClient interface {
	ListFormats(ctx context.Context, in *ListFormatsRequest, opts ...grpc.CallOption) (*ListFormatsResponse, error)
	CreateFormat(ctx context.Context, in *CreateFormatRequest, opts ...grpc.CallOption) (*CreateFormatResponse, error)
	UpdateFormat(ctx context.Context, in *UpdateFormatRequest, opts ...grpc.CallOption) (*UpdateFormatResponse, error)
	DeleteFormat(ctx context.Context, in *DeleteFormatRequest, opts ...grpc.CallOption) (*DeleteFormatResponse, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	ScoreRelease(ctx context.Context, in *ScoreReleaseRequest, opts ...grpc.CallOption) (*ScoreReleaseResponse, error)
	ParseQuality(ctx context.Context, in *ParseQualityRequest, opts ...grpc.CallOption) (*ParseQualityResponse, error)
	SyncTrashGuides(ctx context.Context, in *SyncTrashGuidesRequest, opts ...grpc.CallOption) (*SyncTrashGuidesResponse, error)
	ListReleaseProfiles(ctx context.Context, in *ListReleaseProfilesRequest, opts ...grpc.CallOption) (*ListReleaseProfilesResponse, error)
	UpsertReleaseProfile(ctx context.Context, in *UpsertReleaseProfileRequest, opts ...grpc.CallOption) (*UpsertReleaseProfileResponse, error)
	DeleteReleaseProfile(ctx context.Context, in *DeleteReleaseProfileRequest, opts ...grpc.CallOption) (*DeleteReleaseProfileResponse, error)
}

type formatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFormatServiceClient(cc grpc.ClientConnInterface) FormatServiceClient {
	return &formatServiceClient{cc}
}

func (c *formatServiceClient) ListFormats(ctx context.Context, in *ListFormatsRequest, opts ...grpc.CallOption) (*ListFormatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFormatsResponse)
	err := c.cc.Invoke(ctx, FormatService_ListFormats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) CreateFormat(ctx context.Context, in *CreateFormatRequest, opts ...grpc.CallOption) (*CreateFormatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFormatResponse)
	err := c.cc.Invoke(ctx, FormatService_CreateFormat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) UpdateFormat(ctx context.Context, in *UpdateFormatRequest, opts ...grpc.CallOption) (*UpdateFormatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFormatResponse)
	err := c.cc.Invoke(ctx, FormatService_UpdateFormat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) DeleteFormat(ctx context.Context, in *DeleteFormatRequest, opts ...grpc.CallOption) (*DeleteFormatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFormatResponse)
	err := c.cc.Invoke(ctx, FormatService_DeleteFormat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, FormatService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, FormatService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, FormatService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, FormatService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) ScoreRelease(ctx context.Context, in *ScoreReleaseRequest, opts ...grpc.CallOption) (*ScoreReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreReleaseResponse)
	err := c.cc.Invoke(ctx, FormatService_ScoreRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) ParseQuality(ctx context.Context, in *ParseQualityRequest, opts ...grpc.CallOption) (*ParseQualityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseQualityResponse)
	err := c.cc.Invoke(ctx, FormatService_ParseQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) SyncTrashGuides(ctx context.Context, in *SyncTrashGuidesRequest, opts ...grpc.CallOption) (*SyncTrashGuidesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncTrashGuidesResponse)
	err := c.cc.Invoke(ctx, FormatService_SyncTrashGuides_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) ListReleaseProfiles(ctx context.Context, in *ListReleaseProfilesRequest, opts ...grpc.CallOption) (*ListReleaseProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReleaseProfilesResponse)
	err := c.cc.Invoke(ctx, FormatService_ListReleaseProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) UpsertReleaseProfile(ctx context.Context, in *UpsertReleaseProfileRequest, opts ...grpc.CallOption) (*UpsertReleaseProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertReleaseProfileResponse)
	err := c.cc.Invoke(ctx, FormatService_UpsertReleaseProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatServiceClient) DeleteReleaseProfile(ctx context.Context, in *DeleteReleaseProfileRequest, opts ...grpc.CallOption) (*DeleteReleaseProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReleaseProfileResponse)
	err := c.cc.Invoke(ctx, FormatService_DeleteReleaseProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormatServiceServer is the server API for FormatService service.
// All implementations must embed UnimplementedFormatServiceServer
// for forward compatibility.
type FormatServiceServer interface {
	ListFormats(context.Context, *ListFormatsRequest) (*ListFormatsResponse, error)
	CreateFormat(context.Context, *CreateFormatRequest) (*CreateFormatResponse, error)
	UpdateFormat(context.Context, *UpdateFormatRequest) (*UpdateFormatResponse, error)
	DeleteFormat(context.Context, *DeleteFormatRequest) (*DeleteFormatResponse, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	ScoreRelease(context.Context, *ScoreReleaseRequest) (*ScoreReleaseResponse, error)
	ParseQuality(context.Context, *ParseQualityRequest) (*ParseQualityResponse, error)
	SyncTrashGuides(context.Context, *SyncTrashGuidesRequest) (*SyncTrashGuidesResponse, error)
	ListReleaseProfiles(context.Context, *ListReleaseProfilesRequest) (*ListReleaseProfilesResponse, error)
	UpsertReleaseProfile(context.Context, *UpsertReleaseProfileRequest) (*UpsertReleaseProfileResponse, error)
	DeleteReleaseProfile(context.Context, *DeleteReleaseProfileRequest) (*DeleteReleaseProfileResponse, error)
	mustEmbedUnimplementedFormatServiceServer()
}

// UnimplementedFormatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFormatServiceServer struct{}

func (UnimplementedFormatServiceServer) ListFormats(context.Context, *ListFormatsRequest) (*ListFormatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFormats not implemented")
}
func (UnimplementedFormatServiceServer) CreateFormat(context.Context, *CreateFormatRequest) (*CreateFormatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFormat not implemented")
}
func (UnimplementedFormatServiceServer) UpdateFormat(context.Context, *UpdateFormatRequest) (*UpdateFormatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFormat not implemented")
}
func (UnimplementedFormatServiceServer) DeleteFormat(context.Context, *DeleteFormatRequest) (*DeleteFormatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFormat not implemented")
}
func (UnimplementedFormatServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedFormatServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedFormatServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedFormatServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedFormatServiceServer) ScoreRelease(context.Context, *ScoreReleaseRequest) (*ScoreReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreRelease not implemented")
}
func (UnimplementedFormatServiceServer) ParseQuality(context.Context, *ParseQualityRequest) (*ParseQualityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseQuality not implemented")
}
func (UnimplementedFormatServiceServer) SyncTrashGuides(context.Context, *SyncTrashGuidesRequest) (*SyncTrashGuidesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncTrashGuides not implemented")
}
func (UnimplementedFormatServiceServer) ListReleaseProfiles(context.Context, *ListReleaseProfilesRequest) (*ListReleaseProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReleaseProfiles not implemented")
}
func (UnimplementedFormatServiceServer) UpsertReleaseProfile(context.Context, *UpsertReleaseProfileRequest) (*UpsertReleaseProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertReleaseProfile not implemented")
}
func (UnimplementedFormatServiceServer) DeleteReleaseProfile(context.Context, *DeleteReleaseProfileRequest) (*DeleteReleaseProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReleaseProfile not implemented")
}
func (UnimplementedFormatServiceServer) mustEmbedUnimplementedFormatServiceServer() {}
func (UnimplementedFormatServiceServer) testEmbeddedByValue()                       {}

// UnsafeFormatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormatServiceServer will
// result in compilation errors.
type UnsafeFormatServiceServer interface {
	mustEmbedUnimplementedFormatServiceServer()
}

func RegisterFormatServiceServer(s grpc.ServiceRegistrar, srv FormatServiceServer) {
	// If the following call pancis, it indicates UnimplementedFormatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FormatService_ServiceDesc, srv)
}

func _FormatService_ListFormats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFormatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).ListFormats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_ListFormats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).ListFormats(ctx, req.(*ListFormatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_CreateFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).CreateFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_CreateFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).CreateFormat(ctx, req.(*CreateFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_UpdateFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).UpdateFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_UpdateFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).UpdateFormat(ctx, req.(*UpdateFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_DeleteFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).DeleteFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_DeleteFormat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).DeleteFormat(ctx, req.(*DeleteFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_ScoreRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).ScoreRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_ScoreRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).ScoreRelease(ctx, req.(*ScoreReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_ParseQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).ParseQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_ParseQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).ParseQuality(ctx, req.(*ParseQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_SyncTrashGuides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTrashGuidesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).SyncTrashGuides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_SyncTrashGuides_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).SyncTrashGuides(ctx, req.(*SyncTrashGuidesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_ListReleaseProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReleaseProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).ListReleaseProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_ListReleaseProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).ListReleaseProfiles(ctx, req.(*ListReleaseProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_UpsertReleaseProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertReleaseProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).UpsertReleaseProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_UpsertReleaseProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).UpsertReleaseProfile(ctx, req.(*UpsertReleaseProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormatService_DeleteReleaseProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReleaseProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatServiceServer).DeleteReleaseProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormatService_DeleteReleaseProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatServiceServer).DeleteReleaseProfile(ctx, req.(*DeleteReleaseProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormatService_ServiceDesc is the grpc.ServiceDesc for FormatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.formats.v1.FormatService",
	HandlerType: (*FormatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFormats",
			Handler:    _FormatService_ListFormats_Handler,
		},
		{
			MethodName: "CreateFormat",
			Handler:    _FormatService_CreateFormat_Handler,
		},
		{
			MethodName: "UpdateFormat",
			Handler:    _FormatService_UpdateFormat_Handler,
		},
		{
			MethodName: "DeleteFormat",
			Handler:    _FormatService_DeleteFormat_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _FormatService_ListProfiles_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _FormatService_CreateProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _FormatService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _FormatService_DeleteProfile_Handler,
		},
		{
			MethodName: "ScoreRelease",
			Handler:    _FormatService_ScoreRelease_Handler,
		},
		{
			MethodName: "ParseQuality",
			Handler:    _FormatService_ParseQuality_Handler,
		},
		{
			MethodName: "SyncTrashGuides",
			Handler:    _FormatService_SyncTrashGuides_Handler,
		},
		{
			MethodName: "ListReleaseProfiles",
			Handler:    _FormatService_ListReleaseProfiles_Handler,
		},
		{
			MethodName: "UpsertReleaseProfile",
			Handler:    _FormatService_UpsertReleaseProfile_Handler,
		},
		{
			MethodName: "DeleteReleaseProfile",
			Handler:    _FormatService_DeleteReleaseProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/formatsv1/formats.proto",
}
