// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/formatsv1/formats.proto

package formatsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rules         []*FormatRule          `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultScore  int32                  `protobuf:"varint,4,opt,name=default_score,json=defaultScore,proto3" json:"default_score,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomFormat) Reset() {
	*x = CustomFormat{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFormat) ProtoMessage() {}

func (x *CustomFormat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFormat.ProtoReflect.Descriptor instead.
func (*CustomFormat) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{0}
}

func (x *CustomFormat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomFormat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomFormat) GetRules() []*FormatRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CustomFormat) GetDefaultScore() int32 {
	if x != nil {
		return x.DefaultScore
	}
	return 0
}

func (x *CustomFormat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CustomFormat) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type FormatRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // "title", "size", "seeders"
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`       // "matches", "contains", "gt", "lt", "gte", "lte"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // regex or comparison value
	Negate        bool                   `protobuf:"varint,4,opt,name=negate,proto3" json:"negate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatRule) Reset() {
	*x = FormatRule{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatRule) ProtoMessage() {}

func (x *FormatRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatRule.ProtoReflect.Descriptor instead.
func (*FormatRule) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{1}
}

func (x *FormatRule) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FormatRule) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *FormatRule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FormatRule) GetNegate() bool {
	if x != nil {
		return x.Negate
	}
	return false
}

type ListFormatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormatsRequest) Reset() {
	*x = ListFormatsRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormatsRequest) ProtoMessage() {}

func (x *ListFormatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormatsRequest.ProtoReflect.Descriptor instead.
func (*ListFormatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{2}
}

type ListFormatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formats       []*CustomFormat        `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormatsResponse) Reset() {
	*x = ListFormatsResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormatsResponse) ProtoMessage() {}

func (x *ListFormatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormatsResponse.ProtoReflect.Descriptor instead.
func (*ListFormatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{3}
}

func (x *ListFormatsResponse) GetFormats() []*CustomFormat {
	if x != nil {
		return x.Formats
	}
	return nil
}

type CreateFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules         []*FormatRule          `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultScore  int32                  `protobuf:"varint,3,opt,name=default_score,json=defaultScore,proto3" json:"default_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormatRequest) Reset() {
	*x = CreateFormatRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormatRequest) ProtoMessage() {}

func (x *CreateFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormatRequest.ProtoReflect.Descriptor instead.
func (*CreateFormatRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFormatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFormatRequest) GetRules() []*FormatRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CreateFormatRequest) GetDefaultScore() int32 {
	if x != nil {
		return x.DefaultScore
	}
	return 0
}

type CreateFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *CustomFormat          `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormatResponse) Reset() {
	*x = CreateFormatResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormatResponse) ProtoMessage() {}

func (x *CreateFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormatResponse.ProtoReflect.Descriptor instead.
func (*CreateFormatResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFormatResponse) GetFormat() *CustomFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

type UpdateFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rules         []*FormatRule          `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultScore  int32                  `protobuf:"varint,4,opt,name=default_score,json=defaultScore,proto3" json:"default_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormatRequest) Reset() {
	*x = UpdateFormatRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormatRequest) ProtoMessage() {}

func (x *UpdateFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormatRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormatRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFormatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFormatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFormatRequest) GetRules() []*FormatRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *UpdateFormatRequest) GetDefaultScore() int32 {
	if x != nil {
		return x.DefaultScore
	}
	return 0
}

type UpdateFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *CustomFormat          `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormatResponse) Reset() {
	*x = UpdateFormatResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormatResponse) ProtoMessage() {}

func (x *UpdateFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormatResponse.ProtoReflect.Descriptor instead.
func (*UpdateFormatResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFormatResponse) GetFormat() *CustomFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

type DeleteFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormatRequest) Reset() {
	*x = DeleteFormatRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormatRequest) ProtoMessage() {}

func (x *DeleteFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormatRequest.ProtoReflect.Descriptor instead.
func (*DeleteFormatRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFormatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormatResponse) Reset() {
	*x = DeleteFormatResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormatResponse) ProtoMessage() {}

func (x *DeleteFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormatResponse.ProtoReflect.Descriptor instead.
func (*DeleteFormatResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{9}
}

type QualityProfile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinScore            int32                  `protobuf:"varint,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	CutoffScore         int32                  `protobuf:"varint,4,opt,name=cutoff_score,json=cutoffScore,proto3" json:"cutoff_score,omitempty"`
	UpgradeAllowed      bool                   `protobuf:"varint,5,opt,name=upgrade_allowed,json=upgradeAllowed,proto3" json:"upgrade_allowed,omitempty"`
	UpgradeDelayMinutes int32                  `protobuf:"varint,6,opt,name=upgrade_delay_minutes,json=upgradeDelayMinutes,proto3" json:"upgrade_delay_minutes,omitempty"`
	FormatScores        map[string]int32       `protobuf:"bytes,7,rep,name=format_scores,json=formatScores,proto3" json:"format_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // format_id → score
	CreatedAt           string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QualityProfile) Reset() {
	*x = QualityProfile{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityProfile) ProtoMessage() {}

func (x *QualityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityProfile.ProtoReflect.Descriptor instead.
func (*QualityProfile) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{10}
}

func (x *QualityProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QualityProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QualityProfile) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *QualityProfile) GetCutoffScore() int32 {
	if x != nil {
		return x.CutoffScore
	}
	return 0
}

func (x *QualityProfile) GetUpgradeAllowed() bool {
	if x != nil {
		return x.UpgradeAllowed
	}
	return false
}

func (x *QualityProfile) GetUpgradeDelayMinutes() int32 {
	if x != nil {
		return x.UpgradeDelayMinutes
	}
	return 0
}

func (x *QualityProfile) GetFormatScores() map[string]int32 {
	if x != nil {
		return x.FormatScores
	}
	return nil
}

func (x *QualityProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QualityProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{11}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*QualityProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{12}
}

func (x *ListProfilesResponse) GetProfiles() []*QualityProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type CreateProfileRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinScore            int32                  `protobuf:"varint,2,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	CutoffScore         int32                  `protobuf:"varint,3,opt,name=cutoff_score,json=cutoffScore,proto3" json:"cutoff_score,omitempty"`
	UpgradeAllowed      bool                   `protobuf:"varint,4,opt,name=upgrade_allowed,json=upgradeAllowed,proto3" json:"upgrade_allowed,omitempty"`
	UpgradeDelayMinutes int32                  `protobuf:"varint,5,opt,name=upgrade_delay_minutes,json=upgradeDelayMinutes,proto3" json:"upgrade_delay_minutes,omitempty"`
	FormatScores        map[string]int32       `protobuf:"bytes,6,rep,name=format_scores,json=formatScores,proto3" json:"format_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *CreateProfileRequest) GetCutoffScore() int32 {
	if x != nil {
		return x.CutoffScore
	}
	return 0
}

func (x *CreateProfileRequest) GetUpgradeAllowed() bool {
	if x != nil {
		return x.UpgradeAllowed
	}
	return false
}

func (x *CreateProfileRequest) GetUpgradeDelayMinutes() int32 {
	if x != nil {
		return x.UpgradeDelayMinutes
	}
	return 0
}

func (x *CreateProfileRequest) GetFormatScores() map[string]int32 {
	if x != nil {
		return x.FormatScores
	}
	return nil
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *QualityProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{14}
}

func (x *CreateProfileResponse) GetProfile() *QualityProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinScore            int32                  `protobuf:"varint,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	CutoffScore         int32                  `protobuf:"varint,4,opt,name=cutoff_score,json=cutoffScore,proto3" json:"cutoff_score,omitempty"`
	UpgradeAllowed      bool                   `protobuf:"varint,5,opt,name=upgrade_allowed,json=upgradeAllowed,proto3" json:"upgrade_allowed,omitempty"`
	UpgradeDelayMinutes int32                  `protobuf:"varint,6,opt,name=upgrade_delay_minutes,json=upgradeDelayMinutes,proto3" json:"upgrade_delay_minutes,omitempty"`
	FormatScores        map[string]int32       `protobuf:"bytes,7,rep,name=format_scores,json=formatScores,proto3" json:"format_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *UpdateProfileRequest) GetCutoffScore() int32 {
	if x != nil {
		return x.CutoffScore
	}
	return 0
}

func (x *UpdateProfileRequest) GetUpgradeAllowed() bool {
	if x != nil {
		return x.UpgradeAllowed
	}
	return false
}

func (x *UpdateProfileRequest) GetUpgradeDelayMinutes() int32 {
	if x != nil {
		return x.UpgradeDelayMinutes
	}
	return 0
}

func (x *UpdateProfileRequest) GetFormatScores() map[string]int32 {
	if x != nil {
		return x.FormatScores
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *QualityProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProfileResponse) GetProfile() *QualityProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{18}
}

type ScoreReleaseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Size             int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Seeders          int32                  `protobuf:"varint,3,opt,name=seeders,proto3" json:"seeders,omitempty"`
	Category         string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory      string                 `protobuf:"bytes,5,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	DownloadProtocol string                 `protobuf:"bytes,6,opt,name=download_protocol,json=downloadProtocol,proto3" json:"download_protocol,omitempty"`
	ProfileId        string                 `protobuf:"bytes,7,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"` // optional, uses first profile if empty
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScoreReleaseRequest) Reset() {
	*x = ScoreReleaseRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreReleaseRequest) ProtoMessage() {}

func (x *ScoreReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreReleaseRequest.ProtoReflect.Descriptor instead.
func (*ScoreReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{19}
}

func (x *ScoreReleaseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScoreReleaseRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ScoreReleaseRequest) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *ScoreReleaseRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ScoreReleaseRequest) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *ScoreReleaseRequest) GetDownloadProtocol() string {
	if x != nil {
		return x.DownloadProtocol
	}
	return ""
}

func (x *ScoreReleaseRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type ScoreReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalScore    int32                  `protobuf:"varint,1,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	QualityScore  int32                  `protobuf:"varint,2,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	FormatScore   int32                  `protobuf:"varint,3,opt,name=format_score,json=formatScore,proto3" json:"format_score,omitempty"`
	FormatMatches []*FormatMatch         `protobuf:"bytes,4,rep,name=format_matches,json=formatMatches,proto3" json:"format_matches,omitempty"`
	Quality       *QualityInfo           `protobuf:"bytes,5,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreReleaseResponse) Reset() {
	*x = ScoreReleaseResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreReleaseResponse) ProtoMessage() {}

func (x *ScoreReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreReleaseResponse.ProtoReflect.Descriptor instead.
func (*ScoreReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{20}
}

func (x *ScoreReleaseResponse) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *ScoreReleaseResponse) GetQualityScore() int32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *ScoreReleaseResponse) GetFormatScore() int32 {
	if x != nil {
		return x.FormatScore
	}
	return 0
}

func (x *ScoreReleaseResponse) GetFormatMatches() []*FormatMatch {
	if x != nil {
		return x.FormatMatches
	}
	return nil
}

func (x *ScoreReleaseResponse) GetQuality() *QualityInfo {
	if x != nil {
		return x.Quality
	}
	return nil
}

type FormatMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatId      string                 `protobuf:"bytes,1,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	FormatName    string                 `protobuf:"bytes,2,opt,name=format_name,json=formatName,proto3" json:"format_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	RuleMatched   string                 `protobuf:"bytes,4,opt,name=rule_matched,json=ruleMatched,proto3" json:"rule_matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatMatch) Reset() {
	*x = FormatMatch{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatMatch) ProtoMessage() {}

func (x *FormatMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatMatch.ProtoReflect.Descriptor instead.
func (*FormatMatch) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{21}
}

func (x *FormatMatch) GetFormatId() string {
	if x != nil {
		return x.FormatId
	}
	return ""
}

func (x *FormatMatch) GetFormatName() string {
	if x != nil {
		return x.FormatName
	}
	return ""
}

func (x *FormatMatch) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *FormatMatch) GetRuleMatched() string {
	if x != nil {
		return x.RuleMatched
	}
	return ""
}

type QualityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    string                 `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"` // "2160p", "1080p", etc.
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`         // "Remux", "BluRay", "WEB-DL", "HDTV"
	Codec         string                 `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`           // "h264", "hevc", "av1"
	Hdr           bool                   `protobuf:"varint,4,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Score         int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityInfo) Reset() {
	*x = QualityInfo{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityInfo) ProtoMessage() {}

func (x *QualityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityInfo.ProtoReflect.Descriptor instead.
func (*QualityInfo) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{22}
}

func (x *QualityInfo) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *QualityInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QualityInfo) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *QualityInfo) GetHdr() bool {
	if x != nil {
		return x.Hdr
	}
	return false
}

func (x *QualityInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *QualityInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ParseQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseQualityRequest) Reset() {
	*x = ParseQualityRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseQualityRequest) ProtoMessage() {}

func (x *ParseQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseQualityRequest.ProtoReflect.Descriptor instead.
func (*ParseQualityRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{23}
}

func (x *ParseQualityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ParseQualityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       *QualityInfo           `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseQualityResponse) Reset() {
	*x = ParseQualityResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseQualityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseQualityResponse) ProtoMessage() {}

func (x *ParseQualityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseQualityResponse.ProtoReflect.Descriptor instead.
func (*ParseQualityResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{24}
}

func (x *ParseQualityResponse) GetQuality() *QualityInfo {
	if x != nil {
		return x.Quality
	}
	return nil
}

type SyncTrashGuidesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScoreSet       string                 `protobuf:"bytes,1,opt,name=score_set,json=scoreSet,proto3" json:"score_set,omitempty"`                    // trash_scores key; default "default"
	ImportProfiles bool                   `protobuf:"varint,2,opt,name=import_profiles,json=importProfiles,proto3" json:"import_profiles,omitempty"` // also upsert quality profiles
	Services       []string               `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`                                    // "radarr", "sonarr"; empty = both
	GuidesPath     string                 `protobuf:"bytes,4,opt,name=guides_path,json=guidesPath,proto3" json:"guides_path,omitempty"`              // optional local TRaSH Guides root
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncTrashGuidesRequest) Reset() {
	*x = SyncTrashGuidesRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTrashGuidesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTrashGuidesRequest) ProtoMessage() {}

func (x *SyncTrashGuidesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTrashGuidesRequest.ProtoReflect.Descriptor instead.
func (*SyncTrashGuidesRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{25}
}

func (x *SyncTrashGuidesRequest) GetScoreSet() string {
	if x != nil {
		return x.ScoreSet
	}
	return ""
}

func (x *SyncTrashGuidesRequest) GetImportProfiles() bool {
	if x != nil {
		return x.ImportProfiles
	}
	return false
}

func (x *SyncTrashGuidesRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *SyncTrashGuidesRequest) GetGuidesPath() string {
	if x != nil {
		return x.GuidesPath
	}
	return ""
}

type SyncTrashGuidesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FormatsUpserted  int32                  `protobuf:"varint,1,opt,name=formats_upserted,json=formatsUpserted,proto3" json:"formats_upserted,omitempty"`
	FormatsSkipped   int32                  `protobuf:"varint,2,opt,name=formats_skipped,json=formatsSkipped,proto3" json:"formats_skipped,omitempty"`
	ProfilesUpserted int32                  `protobuf:"varint,3,opt,name=profiles_upserted,json=profilesUpserted,proto3" json:"profiles_upserted,omitempty"`
	GuidesPath       string                 `protobuf:"bytes,4,opt,name=guides_path,json=guidesPath,proto3" json:"guides_path,omitempty"`
	Warnings         []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncTrashGuidesResponse) Reset() {
	*x = SyncTrashGuidesResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTrashGuidesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTrashGuidesResponse) ProtoMessage() {}

func (x *SyncTrashGuidesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTrashGuidesResponse.ProtoReflect.Descriptor instead.
func (*SyncTrashGuidesResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{26}
}

func (x *SyncTrashGuidesResponse) GetFormatsUpserted() int32 {
	if x != nil {
		return x.FormatsUpserted
	}
	return 0
}

func (x *SyncTrashGuidesResponse) GetFormatsSkipped() int32 {
	if x != nil {
		return x.FormatsSkipped
	}
	return 0
}

func (x *SyncTrashGuidesResponse) GetProfilesUpserted() int32 {
	if x != nil {
		return x.ProfilesUpserted
	}
	return 0
}

func (x *SyncTrashGuidesResponse) GetGuidesPath() string {
	if x != nil {
		return x.GuidesPath
	}
	return ""
}

func (x *SyncTrashGuidesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ReleaseProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Preferred      []string               `protobuf:"bytes,3,rep,name=preferred,proto3" json:"preferred,omitempty"`
	MustContain    []string               `protobuf:"bytes,4,rep,name=must_contain,json=mustContain,proto3" json:"must_contain,omitempty"`
	MustNotContain []string               `protobuf:"bytes,5,rep,name=must_not_contain,json=mustNotContain,proto3" json:"must_not_contain,omitempty"`
	PreferredScore int32                  `protobuf:"varint,6,opt,name=preferred_score,json=preferredScore,proto3" json:"preferred_score,omitempty"`
	Enabled        bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseProfile) Reset() {
	*x = ReleaseProfile{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProfile) ProtoMessage() {}

func (x *ReleaseProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProfile.ProtoReflect.Descriptor instead.
func (*ReleaseProfile) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{27}
}

func (x *ReleaseProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReleaseProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReleaseProfile) GetPreferred() []string {
	if x != nil {
		return x.Preferred
	}
	return nil
}

func (x *ReleaseProfile) GetMustContain() []string {
	if x != nil {
		return x.MustContain
	}
	return nil
}

func (x *ReleaseProfile) GetMustNotContain() []string {
	if x != nil {
		return x.MustNotContain
	}
	return nil
}

func (x *ReleaseProfile) GetPreferredScore() int32 {
	if x != nil {
		return x.PreferredScore
	}
	return 0
}

func (x *ReleaseProfile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListReleaseProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleaseProfilesRequest) Reset() {
	*x = ListReleaseProfilesRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleaseProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleaseProfilesRequest) ProtoMessage() {}

func (x *ListReleaseProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleaseProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListReleaseProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{28}
}

type ListReleaseProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ReleaseProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleaseProfilesResponse) Reset() {
	*x = ListReleaseProfilesResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleaseProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleaseProfilesResponse) ProtoMessage() {}

func (x *ListReleaseProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleaseProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListReleaseProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{29}
}

func (x *ListReleaseProfilesResponse) GetProfiles() []*ReleaseProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpsertReleaseProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Preferred      []string               `protobuf:"bytes,3,rep,name=preferred,proto3" json:"preferred,omitempty"`
	MustContain    []string               `protobuf:"bytes,4,rep,name=must_contain,json=mustContain,proto3" json:"must_contain,omitempty"`
	MustNotContain []string               `protobuf:"bytes,5,rep,name=must_not_contain,json=mustNotContain,proto3" json:"must_not_contain,omitempty"`
	PreferredScore int32                  `protobuf:"varint,6,opt,name=preferred_score,json=preferredScore,proto3" json:"preferred_score,omitempty"`
	Enabled        *bool                  `protobuf:"varint,7,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertReleaseProfileRequest) Reset() {
	*x = UpsertReleaseProfileRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertReleaseProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertReleaseProfileRequest) ProtoMessage() {}

func (x *UpsertReleaseProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertReleaseProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertReleaseProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{30}
}

func (x *UpsertReleaseProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertReleaseProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertReleaseProfileRequest) GetPreferred() []string {
	if x != nil {
		return x.Preferred
	}
	return nil
}

func (x *UpsertReleaseProfileRequest) GetMustContain() []string {
	if x != nil {
		return x.MustContain
	}
	return nil
}

func (x *UpsertReleaseProfileRequest) GetMustNotContain() []string {
	if x != nil {
		return x.MustNotContain
	}
	return nil
}

func (x *UpsertReleaseProfileRequest) GetPreferredScore() int32 {
	if x != nil {
		return x.PreferredScore
	}
	return 0
}

func (x *UpsertReleaseProfileRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type UpsertReleaseProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ReleaseProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertReleaseProfileResponse) Reset() {
	*x = UpsertReleaseProfileResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertReleaseProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertReleaseProfileResponse) ProtoMessage() {}

func (x *UpsertReleaseProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertReleaseProfileResponse.ProtoReflect.Descriptor instead.
func (*UpsertReleaseProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{31}
}

func (x *UpsertReleaseProfileResponse) GetProfile() *ReleaseProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteReleaseProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReleaseProfileRequest) Reset() {
	*x = DeleteReleaseProfileRequest{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReleaseProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReleaseProfileRequest) ProtoMessage() {}

func (x *DeleteReleaseProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReleaseProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteReleaseProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteReleaseProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReleaseProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReleaseProfileResponse) Reset() {
	*x = DeleteReleaseProfileResponse{}
	mi := &file_proto_formatsv1_formats_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReleaseProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReleaseProfileResponse) ProtoMessage() {}

func (x *DeleteReleaseProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_formatsv1_formats_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReleaseProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteReleaseProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_formatsv1_formats_proto_rawDescGZIP(), []int{33}
}

var File_proto_formatsv1_formats_proto protoreflect.FileDescriptor

const file_proto_formatsv1_formats_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/formatsv1/formats.proto\x12\x12muxcore.formats.v1\"\xcb\x01\n" +
	"\fCustomFormat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x05rules\x18\x03 \x03(\v2\x1e.muxcore.formats.v1.FormatRuleR\x05rules\x12#\n" +
	"\rdefault_score\x18\x04 \x01(\x05R\fdefaultScore\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"`\n" +
	"\n" +
	"FormatRule\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06negate\x18\x04 \x01(\bR\x06negate\"\x14\n" +
	"\x12ListFormatsRequest\"Q\n" +
	"\x13ListFormatsResponse\x12:\n" +
	"\aformats\x18\x01 \x03(\v2 .muxcore.formats.v1.CustomFormatR\aformats\"\x84\x01\n" +
	"\x13CreateFormatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x05rules\x18\x02 \x03(\v2\x1e.muxcore.formats.v1.FormatRuleR\x05rules\x12#\n" +
	"\rdefault_score\x18\x03 \x01(\x05R\fdefaultScore\"P\n" +
	"\x14CreateFormatResponse\x128\n" +
	"\x06format\x18\x01 \x01(\v2 .muxcore.formats.v1.CustomFormatR\x06format\"\x94\x01\n" +
	"\x13UpdateFormatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x05rules\x18\x03 \x03(\v2\x1e.muxcore.formats.v1.FormatRuleR\x05rules\x12#\n" +
	"\rdefault_score\x18\x04 \x01(\x05R\fdefaultScore\"P\n" +
	"\x14UpdateFormatResponse\x128\n" +
	"\x06format\x18\x01 \x01(\v2 .muxcore.formats.v1.CustomFormatR\x06format\"%\n" +
	"\x13DeleteFormatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteFormatResponse\"\xab\x03\n" +
	"\x0eQualityProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x05R\bminScore\x12!\n" +
	"\fcutoff_score\x18\x04 \x01(\x05R\vcutoffScore\x12'\n" +
	"\x0fupgrade_allowed\x18\x05 \x01(\bR\x0eupgradeAllowed\x122\n" +
	"\x15upgrade_delay_minutes\x18\x06 \x01(\x05R\x13upgradeDelayMinutes\x12Y\n" +
	"\rformat_scores\x18\a \x03(\v24.muxcore.formats.v1.QualityProfile.FormatScoresEntryR\fformatScores\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x1a?\n" +
	"\x11FormatScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x15\n" +
	"\x13ListProfilesRequest\"V\n" +
	"\x14ListProfilesResponse\x12>\n" +
	"\bprofiles\x18\x01 \x03(\v2\".muxcore.formats.v1.QualityProfileR\bprofiles\"\xe9\x02\n" +
	"\x14CreateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmin_score\x18\x02 \x01(\x05R\bminScore\x12!\n" +
	"\fcutoff_score\x18\x03 \x01(\x05R\vcutoffScore\x12'\n" +
	"\x0fupgrade_allowed\x18\x04 \x01(\bR\x0eupgradeAllowed\x122\n" +
	"\x15upgrade_delay_minutes\x18\x05 \x01(\x05R\x13upgradeDelayMinutes\x12_\n" +
	"\rformat_scores\x18\x06 \x03(\v2:.muxcore.formats.v1.CreateProfileRequest.FormatScoresEntryR\fformatScores\x1a?\n" +
	"\x11FormatScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"U\n" +
	"\x15CreateProfileResponse\x12<\n" +
	"\aprofile\x18\x01 \x01(\v2\".muxcore.formats.v1.QualityProfileR\aprofile\"\xf9\x02\n" +
	"\x14UpdateProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x05R\bminScore\x12!\n" +
	"\fcutoff_score\x18\x04 \x01(\x05R\vcutoffScore\x12'\n" +
	"\x0fupgrade_allowed\x18\x05 \x01(\bR\x0eupgradeAllowed\x122\n" +
	"\x15upgrade_delay_minutes\x18\x06 \x01(\x05R\x13upgradeDelayMinutes\x12_\n" +
	"\rformat_scores\x18\a \x03(\v2:.muxcore.formats.v1.UpdateProfileRequest.FormatScoresEntryR\fformatScores\x1a?\n" +
	"\x11FormatScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"U\n" +
	"\x15UpdateProfileResponse\x12<\n" +
	"\aprofile\x18\x01 \x01(\v2\".muxcore.formats.v1.QualityProfileR\aprofile\"&\n" +
	"\x14DeleteProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteProfileResponse\"\xe4\x01\n" +
	"\x13ScoreReleaseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x18\n" +
	"\aseeders\x18\x03 \x01(\x05R\aseeders\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x05 \x01(\tR\vsubCategory\x12+\n" +
	"\x11download_protocol\x18\x06 \x01(\tR\x10downloadProtocol\x12\x1d\n" +
	"\n" +
	"profile_id\x18\a \x01(\tR\tprofileId\"\x82\x02\n" +
	"\x14ScoreReleaseResponse\x12\x1f\n" +
	"\vtotal_score\x18\x01 \x01(\x05R\n" +
	"totalScore\x12#\n" +
	"\rquality_score\x18\x02 \x01(\x05R\fqualityScore\x12!\n" +
	"\fformat_score\x18\x03 \x01(\x05R\vformatScore\x12F\n" +
	"\x0eformat_matches\x18\x04 \x03(\v2\x1f.muxcore.formats.v1.FormatMatchR\rformatMatches\x129\n" +
	"\aquality\x18\x05 \x01(\v2\x1f.muxcore.formats.v1.QualityInfoR\aquality\"\x84\x01\n" +
	"\vFormatMatch\x12\x1b\n" +
	"\tformat_id\x18\x01 \x01(\tR\bformatId\x12\x1f\n" +
	"\vformat_name\x18\x02 \x01(\tR\n" +
	"formatName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12!\n" +
	"\frule_matched\x18\x04 \x01(\tR\vruleMatched\"\x99\x01\n" +
	"\vQualityInfo\x12\x1e\n" +
	"\n" +
	"resolution\x18\x01 \x01(\tR\n" +
	"resolution\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codec\x12\x10\n" +
	"\x03hdr\x18\x04 \x01(\bR\x03hdr\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\"+\n" +
	"\x13ParseQualityRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"Q\n" +
	"\x14ParseQualityResponse\x129\n" +
	"\aquality\x18\x01 \x01(\v2\x1f.muxcore.formats.v1.QualityInfoR\aquality\"\x9b\x01\n" +
	"\x16SyncTrashGuidesRequest\x12\x1b\n" +
	"\tscore_set\x18\x01 \x01(\tR\bscoreSet\x12'\n" +
	"\x0fimport_profiles\x18\x02 \x01(\bR\x0eimportProfiles\x12\x1a\n" +
	"\bservices\x18\x03 \x03(\tR\bservices\x12\x1f\n" +
	"\vguides_path\x18\x04 \x01(\tR\n" +
	"guidesPath\"\xd7\x01\n" +
	"\x17SyncTrashGuidesResponse\x12)\n" +
	"\x10formats_upserted\x18\x01 \x01(\x05R\x0fformatsUpserted\x12'\n" +
	"\x0fformats_skipped\x18\x02 \x01(\x05R\x0eformatsSkipped\x12+\n" +
	"\x11profiles_upserted\x18\x03 \x01(\x05R\x10profilesUpserted\x12\x1f\n" +
	"\vguides_path\x18\x04 \x01(\tR\n" +
	"guidesPath\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"\xe2\x01\n" +
	"\x0eReleaseProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpreferred\x18\x03 \x03(\tR\tpreferred\x12!\n" +
	"\fmust_contain\x18\x04 \x03(\tR\vmustContain\x12(\n" +
	"\x10must_not_contain\x18\x05 \x03(\tR\x0emustNotContain\x12'\n" +
	"\x0fpreferred_score\x18\x06 \x01(\x05R\x0epreferredScore\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"\x1c\n" +
	"\x1aListReleaseProfilesRequest\"]\n" +
	"\x1bListReleaseProfilesResponse\x12>\n" +
	"\bprofiles\x18\x01 \x03(\v2\".muxcore.formats.v1.ReleaseProfileR\bprofiles\"\x80\x02\n" +
	"\x1bUpsertReleaseProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpreferred\x18\x03 \x03(\tR\tpreferred\x12!\n" +
	"\fmust_contain\x18\x04 \x03(\tR\vmustContain\x12(\n" +
	"\x10must_not_contain\x18\x05 \x03(\tR\x0emustNotContain\x12'\n" +
	"\x0fpreferred_score\x18\x06 \x01(\x05R\x0epreferredScore\x12\x1d\n" +
	"\aenabled\x18\a \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"\\\n" +
	"\x1cUpsertReleaseProfileResponse\x12<\n" +
	"\aprofile\x18\x01 \x01(\v2\".muxcore.formats.v1.ReleaseProfileR\aprofile\"-\n" +
	"\x1bDeleteReleaseProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cDeleteReleaseProfileResponse2\xcd\v\n" +
	"\rFormatService\x12^\n" +
	"\vListFormats\x12&.muxcore.formats.v1.ListFormatsRequest\x1a'.muxcore.formats.v1.ListFormatsResponse\x12a\n" +
	"\fCreateFormat\x12'.muxcore.formats.v1.CreateFormatRequest\x1a(.muxcore.formats.v1.CreateFormatResponse\x12a\n" +
	"\fUpdateFormat\x12'.muxcore.formats.v1.UpdateFormatRequest\x1a(.muxcore.formats.v1.UpdateFormatResponse\x12a\n" +
	"\fDeleteFormat\x12'.muxcore.formats.v1.DeleteFormatRequest\x1a(.muxcore.formats.v1.DeleteFormatResponse\x12a\n" +
	"\fListProfiles\x12'.muxcore.formats.v1.ListProfilesRequest\x1a(.muxcore.formats.v1.ListProfilesResponse\x12d\n" +
	"\rCreateProfile\x12(.muxcore.formats.v1.CreateProfileRequest\x1a).muxcore.formats.v1.CreateProfileResponse\x12d\n" +
	"\rUpdateProfile\x12(.muxcore.formats.v1.UpdateProfileRequest\x1a).muxcore.formats.v1.UpdateProfileResponse\x12d\n" +
	"\rDeleteProfile\x12(.muxcore.formats.v1.DeleteProfileRequest\x1a).muxcore.formats.v1.DeleteProfileResponse\x12a\n" +
	"\fScoreRelease\x12'.muxcore.formats.v1.ScoreReleaseRequest\x1a(.muxcore.formats.v1.ScoreReleaseResponse\x12a\n" +
	"\fParseQuality\x12'.muxcore.formats.v1.ParseQualityRequest\x1a(.muxcore.formats.v1.ParseQualityResponse\x12j\n" +
	"\x0fSyncTrashGuides\x12*.muxcore.formats.v1.SyncTrashGuidesRequest\x1a+.muxcore.formats.v1.SyncTrashGuidesResponse\x12v\n" +
	"\x13ListReleaseProfiles\x12..muxcore.formats.v1.ListReleaseProfilesRequest\x1a/.muxcore.formats.v1.ListReleaseProfilesResponse\x12y\n" +
	"\x14UpsertReleaseProfile\x12/.muxcore.formats.v1.UpsertReleaseProfileRequest\x1a0.muxcore.formats.v1.UpsertReleaseProfileResponse\x12y\n" +
	"\x14DeleteReleaseProfile\x12/.muxcore.formats.v1.DeleteReleaseProfileRequest\x1a0.muxcore.formats.v1.DeleteReleaseProfileResponseBIZGgithub.com/Muxcore-Media/media-custom-formats/proto/formatsv1;formatsv1b\x06proto3"

var (
	file_proto_formatsv1_formats_proto_rawDescOnce sync.Once
	file_proto_formatsv1_formats_proto_rawDescData []byte
)

func file_proto_formatsv1_formats_proto_rawDescGZIP() []byte {
	file_proto_formatsv1_formats_proto_rawDescOnce.Do(func() {
		file_proto_formatsv1_formats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_formatsv1_formats_proto_rawDesc), len(file_proto_formatsv1_formats_proto_rawDesc)))
	})
	return file_proto_formatsv1_formats_proto_rawDescData
}

var file_proto_formatsv1_formats_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_formatsv1_formats_proto_goTypes = []any{
	(*CustomFormat)(nil),                 // 0: muxcore.formats.v1.CustomFormat
	(*FormatRule)(nil),                   // 1: muxcore.formats.v1.FormatRule
	(*ListFormatsRequest)(nil),           // 2: muxcore.formats.v1.ListFormatsRequest
	(*ListFormatsResponse)(nil),          // 3: muxcore.formats.v1.ListFormatsResponse
	(*CreateFormatRequest)(nil),          // 4: muxcore.formats.v1.CreateFormatRequest
	(*CreateFormatResponse)(nil),         // 5: muxcore.formats.v1.CreateFormatResponse
	(*UpdateFormatRequest)(nil),          // 6: muxcore.formats.v1.UpdateFormatRequest
	(*UpdateFormatResponse)(nil),         // 7: muxcore.formats.v1.UpdateFormatResponse
	(*DeleteFormatRequest)(nil),          // 8: muxcore.formats.v1.DeleteFormatRequest
	(*DeleteFormatResponse)(nil),         // 9: muxcore.formats.v1.DeleteFormatResponse
	(*QualityProfile)(nil),               // 10: muxcore.formats.v1.QualityProfile
	(*ListProfilesRequest)(nil),          // 11: muxcore.formats.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),         // 12: muxcore.formats.v1.ListProfilesResponse
	(*CreateProfileRequest)(nil),         // 13: muxcore.formats.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),        // 14: muxcore.formats.v1.CreateProfileResponse
	(*UpdateProfileRequest)(nil),         // 15: muxcore.formats.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 16: muxcore.formats.v1.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),         // 17: muxcore.formats.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),        // 18: muxcore.formats.v1.DeleteProfileResponse
	(*ScoreReleaseRequest)(nil),          // 19: muxcore.formats.v1.ScoreReleaseRequest
	(*ScoreReleaseResponse)(nil),         // 20: muxcore.formats.v1.ScoreReleaseResponse
	(*FormatMatch)(nil),                  // 21: muxcore.formats.v1.FormatMatch
	(*QualityInfo)(nil),                  // 22: muxcore.formats.v1.QualityInfo
	(*ParseQualityRequest)(nil),          // 23: muxcore.formats.v1.ParseQualityRequest
	(*ParseQualityResponse)(nil),         // 24: muxcore.formats.v1.ParseQualityResponse
	(*SyncTrashGuidesRequest)(nil),       // 25: muxcore.formats.v1.SyncTrashGuidesRequest
	(*SyncTrashGuidesResponse)(nil),      // 26: muxcore.formats.v1.SyncTrashGuidesResponse
	(*ReleaseProfile)(nil),               // 27: muxcore.formats.v1.ReleaseProfile
	(*ListReleaseProfilesRequest)(nil),   // 28: muxcore.formats.v1.ListReleaseProfilesRequest
	(*ListReleaseProfilesResponse)(nil),  // 29: muxcore.formats.v1.ListReleaseProfilesResponse
	(*UpsertReleaseProfileRequest)(nil),  // 30: muxcore.formats.v1.UpsertReleaseProfileRequest
	(*UpsertReleaseProfileResponse)(nil), // 31: muxcore.formats.v1.UpsertReleaseProfileResponse
	(*DeleteReleaseProfileRequest)(nil),  // 32: muxcore.formats.v1.DeleteReleaseProfileRequest
	(*DeleteReleaseProfileResponse)(nil), // 33: muxcore.formats.v1.DeleteReleaseProfileResponse
	nil,                                  // 34: muxcore.formats.v1.QualityProfile.FormatScoresEntry
	nil,                                  // 35: muxcore.formats.v1.CreateProfileRequest.FormatScoresEntry
	nil,                                  // 36: muxcore.formats.v1.UpdateProfileRequest.FormatScoresEntry
}
var file_proto_formatsv1_formats_proto_depIdxs = []int32{
	1,  // 0: muxcore.formats.v1.CustomFormat.rules:type_name -> muxcore.formats.v1.FormatRule
	0,  // 1: muxcore.formats.v1.ListFormatsResponse.formats:type_name -> muxcore.formats.v1.CustomFormat
	1,  // 2: muxcore.formats.v1.CreateFormatRequest.rules:type_name -> muxcore.formats.v1.FormatRule
	0,  // 3: muxcore.formats.v1.CreateFormatResponse.format:type_name -> muxcore.formats.v1.CustomFormat
	1,  // 4: muxcore.formats.v1.UpdateFormatRequest.rules:type_name -> muxcore.formats.v1.FormatRule
	0,  // 5: muxcore.formats.v1.UpdateFormatResponse.format:type_name -> muxcore.formats.v1.CustomFormat
	34, // 6: muxcore.formats.v1.QualityProfile.format_scores:type_name -> muxcore.formats.v1.QualityProfile.FormatScoresEntry
	10, // 7: muxcore.formats.v1.ListProfilesResponse.profiles:type_name -> muxcore.formats.v1.QualityProfile
	35, // 8: muxcore.formats.v1.CreateProfileRequest.format_scores:type_name -> muxcore.formats.v1.CreateProfileRequest.FormatScoresEntry
	10, // 9: muxcore.formats.v1.CreateProfileResponse.profile:type_name -> muxcore.formats.v1.QualityProfile
	36, // 10: muxcore.formats.v1.UpdateProfileRequest.format_scores:type_name -> muxcore.formats.v1.UpdateProfileRequest.FormatScoresEntry
	10, // 11: muxcore.formats.v1.UpdateProfileResponse.profile:type_name -> muxcore.formats.v1.QualityProfile
	21, // 12: muxcore.formats.v1.ScoreReleaseResponse.format_matches:type_name -> muxcore.formats.v1.FormatMatch
	22, // 13: muxcore.formats.v1.ScoreReleaseResponse.quality:type_name -> muxcore.formats.v1.QualityInfo
	22, // 14: muxcore.formats.v1.ParseQualityResponse.quality:type_name -> muxcore.formats.v1.QualityInfo
	27, // 15: muxcore.formats.v1.ListReleaseProfilesResponse.profiles:type_name -> muxcore.formats.v1.ReleaseProfile
	27, // 16: muxcore.formats.v1.UpsertReleaseProfileResponse.profile:type_name -> muxcore.formats.v1.ReleaseProfile
	2,  // 17: muxcore.formats.v1.FormatService.ListFormats:input_type -> muxcore.formats.v1.ListFormatsRequest
	4,  // 18: muxcore.formats.v1.FormatService.CreateFormat:input_type -> muxcore.formats.v1.CreateFormatRequest
	6,  // 19: muxcore.formats.v1.FormatService.UpdateFormat:input_type -> muxcore.formats.v1.UpdateFormatRequest
	8,  // 20: muxcore.formats.v1.FormatService.DeleteFormat:input_type -> muxcore.formats.v1.DeleteFormatRequest
	11, // 21: muxcore.formats.v1.FormatService.ListProfiles:input_type -> muxcore.formats.v1.ListProfilesRequest
	13, // 22: muxcore.formats.v1.FormatService.CreateProfile:input_type -> muxcore.formats.v1.CreateProfileRequest
	15, // 23: muxcore.formats.v1.FormatService.UpdateProfile:input_type -> muxcore.formats.v1.UpdateProfileRequest
	17, // 24: muxcore.formats.v1.FormatService.DeleteProfile:input_type -> muxcore.formats.v1.DeleteProfileRequest
	19, // 25: muxcore.formats.v1.FormatService.ScoreRelease:input_type -> muxcore.formats.v1.ScoreReleaseRequest
	23, // 26: muxcore.formats.v1.FormatService.ParseQuality:input_type -> muxcore.formats.v1.ParseQualityRequest
	25, // 27: muxcore.formats.v1.FormatService.SyncTrashGuides:input_type -> muxcore.formats.v1.SyncTrashGuidesRequest
	28, // 28: muxcore.formats.v1.FormatService.ListReleaseProfiles:input_type -> muxcore.formats.v1.ListReleaseProfilesRequest
	30, // 29: muxcore.formats.v1.FormatService.UpsertReleaseProfile:input_type -> muxcore.formats.v1.UpsertReleaseProfileRequest
	32, // 30: muxcore.formats.v1.FormatService.DeleteReleaseProfile:input_type -> muxcore.formats.v1.DeleteReleaseProfileRequest
	3,  // 31: muxcore.formats.v1.FormatService.ListFormats:output_type -> muxcore.formats.v1.ListFormatsResponse
	5,  // 32: muxcore.formats.v1.FormatService.CreateFormat:output_type -> muxcore.formats.v1.CreateFormatResponse
	7,  // 33: muxcore.formats.v1.FormatService.UpdateFormat:output_type -> muxcore.formats.v1.UpdateFormatResponse
	9,  // 34: muxcore.formats.v1.FormatService.DeleteFormat:output_type -> muxcore.formats.v1.DeleteFormatResponse
	12, // 35: muxcore.formats.v1.FormatService.ListProfiles:output_type -> muxcore.formats.v1.ListProfilesResponse
	14, // 36: muxcore.formats.v1.FormatService.CreateProfile:output_type -> muxcore.formats.v1.CreateProfileResponse
	16, // 37: muxcore.formats.v1.FormatService.UpdateProfile:output_type -> muxcore.formats.v1.UpdateProfileResponse
	18, // 38: muxcore.formats.v1.FormatService.DeleteProfile:output_type -> muxcore.formats.v1.DeleteProfileResponse
	20, // 39: muxcore.formats.v1.FormatService.ScoreRelease:output_type -> muxcore.formats.v1.ScoreReleaseResponse
	24, // 40: muxcore.formats.v1.FormatService.ParseQuality:output_type -> muxcore.formats.v1.ParseQualityResponse
	26, // 41: muxcore.formats.v1.FormatService.SyncTrashGuides:output_type -> muxcore.formats.v1.SyncTrashGuidesResponse
	29, // 42: muxcore.formats.v1.FormatService.ListReleaseProfiles:output_type -> muxcore.formats.v1.ListReleaseProfilesResponse
	31, // 43: muxcore.formats.v1.FormatService.UpsertReleaseProfile:output_type -> muxcore.formats.v1.UpsertReleaseProfileResponse
	33, // 44: muxcore.formats.v1.FormatService.DeleteReleaseProfile:output_type -> muxcore.formats.v1.DeleteReleaseProfileResponse
	31, // [31:45] is the sub-list for method output_type
	17, // [17:31] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_formatsv1_formats_proto_init() }
func file_proto_formatsv1_formats_proto_init() {
	if File_proto_formatsv1_formats_proto != nil {
		return
	}
	file_proto_formatsv1_formats_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_formatsv1_formats_proto_rawDesc), len(file_proto_formatsv1_formats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_formatsv1_formats_proto_goTypes,
		DependencyIndexes: file_proto_formatsv1_formats_proto_depIdxs,
		MessageInfos:      file_proto_formatsv1_formats_proto_msgTypes,
	}.Build()
	File_proto_formatsv1_formats_proto = out.File
	file_proto_formatsv1_formats_proto_goTypes = nil
	file_proto_formatsv1_formats_proto_depIdxs = nil
}
